import React from 'react';
import { PolicyDocument, FAQItem } from '../types';

export const POLICIES_DATA: PolicyDocument[] = [
  {
    id: 'privacy',
    title: 'Privacy Policy',
    lastUpdated: 'September 16, 2026',
    summary: 'Strictly compliant with Apple App Store Guidelines 5.1.1 and Google Play Developer Policies. Outlines data collection, third-party SDKs, and your data protection rights.',
    content: (
      <div className="space-y-6 text-[#4A5157] leading-relaxed text-sm md:text-base">
        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">1. Overview & Commitment</h4>
          <p>
            Monik Studio (&quot;we&quot;, &quot;our&quot;, or &quot;us&quot;) is dedicated to protecting the privacy and personal data of players and users across our mobile applications, mobile games, and digital services.
          </p>
          <p className="mt-2">
            This Privacy Policy explains how we collect, handle, disclose, and safeguard your information when you download, install, or use mobile applications and games published by Monik Studio on the Apple App Store, Google Play Store, or other authorized platforms.
          </p>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">2. Information We Collect</h4>
          <ul className="list-disc pl-5 space-y-1.5 mt-2">
            <li>
              <strong className="text-[#24282C]">Device & Technical Telemetry:</strong> Device model, operating system version, screen resolution, locale language setting, IP address (truncated for coarse geographic analytics), and battery/memory diagnostics.
            </li>
            <li>
              <strong className="text-[#24282C]">Gameplay & App Usage Data:</strong> Levels cleared, puzzle completion times, high scores, user preferences (e.g., sound/haptics toggles), and non-identifying interaction sessions.
            </li>
            <li>
              <strong className="text-[#24282C]">Purchase Receipts & Virtual Items:</strong> Transaction IDs and purchase tokens generated by Apple App Store and Google Play to unlock premium tiers or in-game content. <em className="text-[#D86950]">We never receive or store your credit card, debit card, or banking details</em>; all financial transactions are processed securely through Apple or Google.
            </li>
            <li>
              <strong className="text-[#24282C]">Voluntary Communication Data:</strong> Name, email address, and message contents when you contact our support desk at{' '}
              <a href="mailto:contact@monikstudio.com" className="font-mono text-[#D86950] underline">contact@monikstudio.com</a>.
            </li>
          </ul>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">3. Third-Party Services & SDK Integrations</h4>
          <p>To enable online leaderboards, cloud backups, and stable mobile performance, our titles may integrate the following vetted service providers:</p>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mt-3">
            <div className="p-3.5 bg-[#FAF8F5] rounded-xl border border-[#EBE5DB]">
              <span className="font-semibold text-[#24282C] block">Apple Game Center</span>
              <span className="text-xs text-[#6B7280]">Achievements, leaderboards & cloud save for iOS users.</span>
            </div>
            <div className="p-3.5 bg-[#FAF8F5] rounded-xl border border-[#EBE5DB]">
              <span className="font-semibold text-[#24282C] block">Google Play Games Services</span>
              <span className="text-xs text-[#6B7280]">Cloud synchronization & achievements on Android.</span>
            </div>
            <div className="p-3.5 bg-[#FAF8F5] rounded-xl border border-[#EBE5DB]">
              <span className="font-semibold text-[#24282C] block">Firebase Crashlytics & Analytics</span>
              <span className="text-xs text-[#6B7280]">Anonymous crash reports and stability diagnostics.</span>
            </div>
            <div className="p-3.5 bg-[#FAF8F5] rounded-xl border border-[#EBE5DB]">
              <span className="font-semibold text-[#24282C] block">Ad Networks (Google AdMob / Unity Ads)</span>
              <span className="text-xs text-[#6B7280]">Contextual ads adhering strictly to Apple ATT and Google Play Families guidelines.</span>
            </div>
          </div>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">4. Children&apos;s Privacy (COPPA & Google Play Families Policy)</h4>
          <p>
            We treat young players&apos; safety with utmost care. Titles labeled as &quot;Everyone&quot; (4+) comply with the Children&apos;s Online Privacy Protection Act (COPPA), the EU GDPR-K, and the Google Play Families Policy. We do not knowingly collect personal information from children under 13 (or under 16 in certain EU jurisdictions).
          </p>
          <p className="mt-2">
            If you believe an underage child has provided personal information through our services without parental consent, please reach out to <strong className="text-[#24282C]">contact@monikstudio.com</strong>, and we will promptly erase the associated records.
          </p>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">5. User Rights & Data Deletion (GDPR & CCPA/CPRA)</h4>
          <p>Under applicable global privacy laws, you possess the right to:</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Request confirmation of whether we hold personal telemetry concerning you.</li>
            <li>Request an electronic copy of your records in a portable format.</li>
            <li>Request rectification of inaccurate data.</li>
            <li>
              <strong className="text-[#24282C]">Request erasure/deletion of your account and saved cloud data</strong> via our in-app settings or via our dedicated online{' '}
              <a 
                href="/data-deletion" 
                onClick={(e) => {
                  e.preventDefault();
                  window.dispatchEvent(new CustomEvent('monik:navigate', { detail: { path: '/data-deletion' } }));
                }}
                className="text-[#D86950] underline font-medium"
              >
                Data Deletion Request portal
              </a>.
            </li>
          </ul>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">6. Contact Information</h4>
          <p>
            If you have any questions, feedback, or inquiries regarding our privacy standards, please contact our designated privacy officer at:
          </p>
          <div className="mt-3 p-4 bg-[#FAF8F5] rounded-xl border border-[#EBE5DB] font-mono text-sm space-y-1">
            <div><strong className="text-[#24282C]">Monik Studio Privacy Team</strong></div>
            <div>Email: <a href="mailto:contact@monikstudio.com" className="text-[#D86950] underline">contact@monikstudio.com</a></div>
            <div>Website: <a href="https://monikstudio.com" target="_blank" rel="noreferrer" className="text-[#779585] underline">https://monikstudio.com</a></div>
          </div>
        </div>
      </div>
    )
  },
  {
    id: 'terms',
    title: 'Terms of Service',
    lastUpdated: 'September 25, 2026',
    summary: 'Rules governing licensing, permitted use, in-app purchases, and auto-renewable subscriptions for Monik Studio mobile applications and games.',
    content: (
      <div className="space-y-6 text-[#4A5157] leading-relaxed text-sm md:text-base">
        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">1. Acceptance of Terms</h4>
          <p>
            By downloading, accessing, or playing any game or mobile app developed by Monik Studio, you agree to be bound by these Terms of Service, along with our Privacy Policy. If you do not agree with these terms, you must refrain from downloading or using our products.
          </p>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">2. End User License Agreement (EULA)</h4>
          <p>
            Monik Studio grants you a personal, revocable, non-exclusive, non-transferable, limited license to download and play our software strictly for your personal, non-commercial entertainment purposes on supported devices.
          </p>
          <p className="mt-2">
            For iOS users, your license is also subject to Apple&apos;s Standard Licensed Application End User License Agreement (EULA) located at Apple&apos;s Legal portal. For Android users, terms are governed additionally by Google Play Terms of Service.
          </p>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">3. Virtual Goods & In-App Purchases</h4>
          <p>
            Certain applications may provide virtual items, cosmetic themes, or premium feature unlocks. All virtual items are licensed, not sold. Virtual goods hold no real-world monetary value and cannot be exchanged, transferred, or refunded outside the explicit refund rules of Apple App Store or Google Play Store.
          </p>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">4. Auto-Renewable Subscriptions (Điều khoản Gói Đăng Ký Tự Gia Hạn)</h4>
          <p>
            Certain Monik Studio apps and games offer premium tiers, ad-free access, VIP features, or exclusive content via auto-renewable subscriptions. By subscribing, you agree to the following terms pursuant to Apple App Store Guideline 3.1.2 and Google Play Store policies:
          </p>
          <div className="mt-3 space-y-3">
            <div className="p-3.5 bg-[#FAF8F5] rounded-xl border border-[#EBE5DB]">
              <strong className="text-[#24282C] text-sm block mb-1">Billing & Payment Confirmation</strong>
              <p className="text-xs text-[#5A626A] leading-relaxed">
                Payment will be charged to your Apple ID / iTunes Account or Google Play Account upon confirmation of purchase. Subscription plans and pricing options (e.g., Weekly, Monthly, Annual) are clearly displayed within the app prior to completing the purchase.
              </p>
            </div>

            <div className="p-3.5 bg-[#FAF8F5] rounded-xl border border-[#EBE5DB]">
              <strong className="text-[#24282C] text-sm block mb-1">Automatic Renewal & Renewal Charges</strong>
              <p className="text-xs text-[#5A626A] leading-relaxed">
                Subscriptions automatically renew for the same duration and price unless auto-renewal is turned off or cancelled at least 24 hours prior to the conclusion of the current billing cycle. Your account will be charged for renewal within the 24-hour period prior to the end of the current period.
              </p>
            </div>

            <div className="p-3.5 bg-[#FAF8F5] rounded-xl border border-[#EBE5DB]">
              <strong className="text-[#24282C] text-sm block mb-1">Free Trial Periods & Forfeiture Policy</strong>
              <p className="text-xs text-[#5A626A] leading-relaxed">
                If an introductory free trial is offered, you will enjoy premium access for the specified trial duration. Any unused portion of a free trial period, if offered, will be forfeited when you purchase a subscription to that publication/product, where applicable. If you do not cancel at least 24 hours before the trial ends, it will convert to a paid auto-renewing subscription.
              </p>
            </div>

            <div className="p-3.5 bg-[#FAF8F5] rounded-xl border border-[#EBE5DB]">
              <strong className="text-[#24282C] text-sm block mb-1">How to Manage & Cancel Subscriptions (Hướng Dẫn Hủy Gia Hạn)</strong>
              <p className="text-xs text-[#5A626A] leading-relaxed mb-2">
                You can manage or cancel your subscription at any time through your device store account settings. <strong className="text-[#D86950]">Uninstalling or deleting the application does not automatically cancel your active subscription.</strong>
              </p>
              <ul className="text-xs text-[#5A626A] list-disc pl-5 space-y-1">
                <li><strong className="text-[#24282C]">On iOS / iPadOS (Apple):</strong> Go to <em>Settings</em> &gt; Tap your <em>[Apple ID / Name]</em> &gt; Tap <em>Subscriptions</em> &gt; Select the Monik Studio subscription &gt; Tap <em>Cancel Subscription</em>.</li>
                <li><strong className="text-[#24282C]">On Android (Google Play):</strong> Open the <em>Google Play Store</em> app &gt; Tap your <em>Profile icon</em> (top right) &gt; Tap <em>Payments &amp; subscriptions</em> &gt; Tap <em>Subscriptions</em> &gt; Select the Monik Studio subscription &gt; Tap <em>Cancel subscription</em>.</li>
              </ul>
              <p className="text-[11px] text-[#8B939E] mt-2">
                Upon cancellation, your subscription remains active until the end of the current billing cycle. You will not be charged again.
              </p>
            </div>

            <div className="p-3.5 bg-[#FAF8F5] rounded-xl border border-[#EBE5DB]">
              <strong className="text-[#24282C] text-sm block mb-1">Refunds & Price Transparency</strong>
              <p className="text-xs text-[#5A626A] leading-relaxed">
                All payment processing and refund requests are governed directly by Apple App Store or Google Play Store policies. Monik Studio does not store or process your financial billing information. In case of price changes, advance notification will be delivered via Apple or Google for your consent before renewal.
              </p>
            </div>
          </div>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">5. User Conduct & Prohibited Activities</h4>
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1 mt-2">
            <li>Reverse engineer, decompile, disassemble, or derive source code from any Monik Studio binary.</li>
            <li>Employ automation scripts, bots, cheat tools, or unauthorized modifications to manipulate game progress.</li>
            <li>Infringe upon copyright, trademarks, or proprietary visual identity belonging to Monik Studio.</li>
          </ul>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">6. Disclaimer of Warranties & Limitation of Liability</h4>
          <p>
            Our applications are provided &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; without warranties of any kind. Monik Studio shall not be liable for any indirect, incidental, or consequential damages arising out of your inability to access or use the services.
          </p>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">7. Contact for Legal Inquiries</h4>
          <p>
            For inquiries regarding our terms, reach us at <a href="mailto:contact@monikstudio.com" className="font-mono text-[#D86950] underline">contact@monikstudio.com</a>.
          </p>
        </div>
      </div>
    )
  },
  {
    id: 'data-deletion',
    title: 'User Data Deletion Instructions',
    lastUpdated: 'September 16, 2026',
    summary: 'Mandatory Google Play Data Safety requirement. Submit your account or player data deletion request or learn how to purge your data directly on device.',
    content: (
      <div className="space-y-6 text-[#4A5157] leading-relaxed text-sm md:text-base">
        <div className="p-4 bg-[#779585]/10 rounded-xl border border-[#779585]/30">
          <h4 className="text-base font-bold text-[#24282C] flex items-center gap-2">
            <span className="w-2 h-2 rounded-full bg-[#779585]"></span>
            Google Play & Apple Store Compliance Notice
          </h4>
          <p className="text-xs md:text-sm text-[#4A5157] mt-1">
            Google Play requires all developers offering account creation or collecting identifiable telemetry to provide a persistent web resource where users can initiate data deletion without reinstalling the app.
          </p>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">Option 1: In-App Self Deletion (Instant)</h4>
          <p>If you still have any Monik Studio app installed on your phone or tablet:</p>
          <ol className="list-decimal pl-5 space-y-1.5 mt-2">
            <li>Launch the Monik Studio game or app.</li>
            <li>Open the <strong className="text-[#24282C]">Settings</strong> (Gear Icon) menu.</li>
            <li>Navigate to <strong className="text-[#24282C]">Account & Privacy</strong>.</li>
            <li>Tap <strong className="text-[#D86950]">Delete My Account & Clear Data</strong> and confirm the warning prompt.</li>
          </ol>
          <p className="mt-2 text-xs text-[#6B7280]">This will instantly purge your cloud save records, player ID, and local game state.</p>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">Option 2: Direct Email Request (If App is Uninstalled)</h4>
          <p>
            If you have uninstalled the app or cannot access your device, you may write directly to our automated processing desk at{' '}
            <strong className="text-[#24282C]">contact@monikstudio.com</strong> with the subject line &quot;Data Deletion Request&quot;.
          </p>
          <p className="mt-2">
            <strong className="text-[#24282C]">What data will be deleted:</strong> Cloud game progress, player profile identifier, telemetry linked to your device identifier, and support conversation logs.
          </p>
          <p className="mt-1">
            <strong className="text-[#24282C]">Data retention exceptions:</strong> Legally mandated financial audit transaction logs maintained by Apple/Google for tax compliance are preserved by Apple/Google under their respective policies.
          </p>
        </div>
      </div>
    )
  },
  {
    id: 'support',
    title: 'App Store & Google Play Support',
    lastUpdated: 'September 16, 2026',
    summary: 'Dedicated support portal for in-app purchase recovery, bug reporting, game saves, and inquiries as required by Apple & Google guidelines.',
    content: (
      <div className="space-y-6 text-[#4A5157] leading-relaxed text-sm md:text-base">
        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">Official Support Contact</h4>
          <p>
            For all technical troubleshooting, bug reports, feature requests, or purchasing assistance across our iOS and Android mobile software, please contact our studio engineering team at:
          </p>
          <div className="mt-3 p-4 bg-[#FAF8F5] rounded-xl border border-[#EBE5DB] flex flex-col gap-1 font-mono text-sm">
            <span className="text-[#24282C] font-semibold">Monik Studio Support Desk</span>
            <span>Email: <a href="mailto:contact@monikstudio.com" className="text-[#D86950] underline">contact@monikstudio.com</a></span>
            <span>Response SLA: Within 24 business hours</span>
          </div>
        </div>

        <div>
          <h4 className="text-lg font-bold text-[#24282C] mb-2">How to Restore In-App Purchases</h4>
          <p>
            If you switched to a new iPhone or Android device and need to restore your unlocked levels, ad-free status, or premium upgrades:
          </p>
          <ul className="list-disc pl-5 space-y-1.5 mt-2">
            <li>Ensure you are logged into the same Apple ID or Google Play Account used during original purchase.</li>
            <li>Open the game or app Settings screen.</li>
            <li>Tap <strong className="text-[#24282C]">&quot;Restore Purchases&quot;</strong>.</li>
            <li>The store will re-validate your receipt and unlock all non-consumable items without charging you again.</li>
          </ul>
        </div>
      </div>
    )
  }
];

export const FAQ_DATA: FAQItem[] = [
  {
    category: 'payments',
    question: 'How do I restore my purchases after reinstalling or switching devices?',
    answer: 'Open the game or app settings screen and tap "Restore Purchases". Make sure you are signed into the exact same Apple ID or Google Play account used during original purchase.'
  },
  {
    category: 'games',
    question: 'Can I play Monik Studio games offline without internet?',
    answer: 'Yes! Titles like Lịch Xưa and Knife Shooter Hit Top are designed to be 100% functional and playable offline without cellular or Wi-Fi connection, making them ideal for airplane mode and daily commutes.'
  },
  {
    category: 'data',
    question: 'How do I request complete deletion of my user and game data?',
    answer: 'You can tap the in-app "Delete Account & Data" option under Settings > Privacy, or email contact@monikstudio.com with the subject "Data Deletion Request". We process all requests within 48 hours.'
  },
  {
    category: 'general',
    question: 'How can I submit feedback or report a bug?',
    answer: 'Send us an email at contact@monikstudio.com with your device model, OS version, and a brief description or screenshot of the issue. Our developers review every report.'
  }
];
